CREATE SCHEMA ECOMMERCE;

SET SCHEMA ECOMMERCE;

CREATE TABLE PRICES (
    PRICE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP,
    RATE INT NOT NULL,
    PRIORITY INT NOT NULL,
    AMOUNT DECIMAL(5,2) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL
);