CREATE TABLE PRICES (
    BRAND_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    RATE INT NOT NULL,
    PRIORITY INT NOT NULL,
    AMOUNT DECIMAL(5,2) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL
);

ALTER TABLE PRICES ADD PRIMARY KEY (BRAND_ID, PRODUCT_ID, START_DATE, END_DATE);